#spring.application.name=RedisApacheCamel

spring:
  application:
    name: RedisApacheCamel

  redis:
    host: localhost
    port: 6379


server:
  port: 8090

  camel:
    springboot:
      main-run-controller: true